### ISSUE TITLE
Cannot dataize simple object

### ISSUE THREAD

**Issue by kerelape** [objectionary/eoc#237]
Getting this error: [1:0] mismatched input '[' expecting {COMMENTARY, META, 'Q', 'QQ', '*', '&lt;', '&amp;', '$', '(', '@', '^', BYTES, BOOL, STRING, INT, FLOAT, HEX, NAME, TEXT}: "[] &gt; main"

main.eo:
```eolang
[] > main
  QQ.io.stdout > @
    "Hello, World!"
```

Running:
```bash
$ eoc dataize main.eo
```

**Comment by maxonfjvipon** [comment]
@kerelape since EO 0.35.0 all named abstract objects (like `main` in your example) must have mandatory comment in front itself. You may check [this issue](https://github.com/objectionary/eo/issues/921) and [this PR](https://github.com/objectionary/eo/pull/2833). 
This feature is not fully implemented yet, but soon all such comments must be at lease 64 characters long.

**Comment by yegor256** [comment]
@maxonfjvipon @kerelape I think it should be this one (with `args`):

```
# This is my awesome object that prints "Hello, World!" to the console.
[args] > main
  QQ.io.stdout > @
    "Hello, World!"
```

**Comment by yegor256** [comment]
@kerelape I believe, it's explained
