### ISSUE TITLE
Compile program without dataization

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eoc#35]
Why I can't compile program like this:
```
eoc link
```
Code
```
[a b] > sum
  plus. > @
    a
    b
```
It fails. I don't want to dataize program. I need only XMIR file.
Here is [log.txt](https://github.com/objectionary/eo/files/9423788/log.txt)

**Comment by ivan-egorov42** [comment]
@mximp Here is the [log.txt](https://github.com/objectionary/eoc/files/9460902/log.txt)

**Comment by mximp** [comment]
@ivan-egorov42 
It seems like during compilation step `eo-maven-plugin` cannot be correctly retrieved (uses fake `0.0.0` version):
```
[37mJava sources generated in /home/ivan/codes/eolang/examples/sum/.eoc/generated-sources[39m
[90m+ /usr/local/lib/node_modules/eolang/mvnw/mvnw compiler:compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Deo.targetDir=/home/ivan/codes/eolang/examples/sum/.eoc -Deo.generatedDir=/home/ivan/codes/eolang/examples/sum/.eoc/generated-sources --errors --batch-mode --update-snapshots --fail-fast[39m
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/eolang/eo-maven-plugin/0.0.0/eo-maven-plugin-0.0.0.pom
[WARNING] The POM for org.eolang:eo-maven-plugin:jar:0.0.0 is missing, no dependency information available
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/eolang/eo-maven-plugin/0.0.0/eo-maven-plugin-0.0.0.jar
[WARNING] Failed to retrieve plugin descriptor for org.eolang:eo-maven-plugin:0.0.0: Plugin org.eolang:eo-maven-plugin:0.0.0 or one of its dependencies could not be resolved: Could not find artifact org.eolang:eo-maven-plugin:jar:0.0.0 in central (https://repo.maven.apache.org/maven2)
```
Due to this compilation of Java classes doesn't happen and hence consequent errors.
I can see that for other eoc commands the EO version is set explicitly:
```
'-Deo.version=' + (opts.parserVersion ? opts.parserVersion : parserVersion()),
```
But for `eoc link` is not. I think we need to fix this

**Comment by ivan-egorov42** [comment]
@mximp ok, you suppose that problem with wrong version of `eo-maven-plugin` in `eoc link`?

**Comment by ivan-egorov42** [comment]
@mximp Now I'm trying to run this code in sandbox and getting the same error. Here is [log.txt (https://github.com/objectionary/eoc/files/9461548/log.txt)

**Comment by ivan-egorov42** [comment]
@yegor256 @Graur please, have a look.

**Comment by mximp** [comment]
> @mximp ok, you suppose that problem with wrong version of `eo-maven-plugin` in `eoc link`?

@ivan-egorov42 No. I mean that this need to be fixed. Latest version has this flaw.

**Comment by ivan-egorov42** [comment]
@mximp ok. So now I can't compile this program?

**Comment by mximp** [comment]
@ivan-egorov42 Would you be able to fix it?

**Comment by ivan-egorov42** [comment]
@mximp I'm not sure) I can wait for solution, it is not urgent.

**Comment by mximp** [comment]
@yasamprom Can you please help with the fix.

**Comment by mximp** [comment]
@yegor256 please assign the task

**Comment by yegor256** [comment]
@yasamprom it's yours, please hel

**Comment by mximp** [comment]
@volodya-lombrozo please assist

**Comment by volodya-lombrozo** [comment]
The problem is quite deeper. I’ve tried to run the same code in `sandbox` and using `eoc` directly:

```eo
[a b] > sum
  plus. > @
    a
    b
```
In both cases we have the same compilation exception.
The problem remains with all EO programs where we don’t use foreign objects. For example, the next code samples will compile fine:
```eo
[a b] > sum
  plus. > @
    a
    b
  QQ.io.stdout > neo
    "Wake up, Neo..."
```

Or

```eo
[a b] > sum
  memory 0 > x
  plus. > @
    a
    b
```

As I mentioned above, in the first code sample we don’t use foreign objects, by that reason our `eo-foreign.json` will contain only one entry:
```json
[
    {
        "id": "sum",
        "discovered": "0",
        "xmir": "/Users/lombrozo/Workspace/EOlang/Projects/sum/.eoc/01-parse/sum.xmir",
        "scope": "compile",
        "eo": "/Users/lombrozo/Workspace/EOlang/Projects/sum/sum.eo",
        "xmir2": "/Users/lombrozo/Workspace/EOlang/Projects/sum/.eoc/03-optimize/sum.xmir",
        "version": "0.0.0"
    }
]
``` 

Therefore the next phases `Discover`,  `Pull`, `Resolve`, `Place` will do nothing.  The key point there is that classpath after all phases will be empty. `eo-runtime` classes will absent and we will see compilation error (since all transpiled classes depend on runtime library). 
I will discover the problem further and will try to suggest a fix.

**Comment by volodya-lombrozo** [comment]
@ivan-egorov42 can you try to run your example program again, please? We fixed that bug from `0.28.11` version.

**Comment by volodya-lombrozo** [comment]
@yegor256 @mximp probably we can close that issue

**Comment by ivan-egorov42** [comment]
@volodya-lombrozo All is OK, thanks!
